version: '3.5'
services:
  peerjs:
    image: node:12
    container_name: peerjs
    expose:
      - '9000'
    command: bash -c "npm install -g peer && peerjs --port 9000 --path /peer"
    networks:
      - vchat_net
  video_chat_backend:
    build: .
    container_name: video_chat_backend
    expose:
      - '5000'
    environment:
      - NODE_ENV=development
    networks:
      - vchat_net

networks:
  vchat_net:
    name: vchat_net
    external: true
